#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


GENERATED_HEADER = (
    "This file is generated by declaude-context-sync/sync_mcp.py from .mcp.json.\n"
    "Do not edit it by hand."
)
GENERATED_MARKERS = (
    "declaude-context-sync/sync_mcp.py",
    "agent-context-tools/sync_mcp.py",
)
BARE_TOML_KEY_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Project Claude-style MCP config into Codex and Gemini configs."
    )
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Path to the repository whose MCP config should be projected.",
    )
    parser.add_argument(
        "--config",
        default=None,
        help="Path to the optional JSON config file for generator settings.",
    )
    parser.add_argument(
        "--source",
        default=".mcp.json",
        help="Path to the source MCP JSON file.",
    )
    parser.add_argument(
        "--gemini-target",
        default=".gemini/settings.json",
        help="Path to the generated Gemini project settings file.",
    )
    parser.add_argument(
        "--codex-target",
        default=".codex/config.toml",
        help="Path to the generated Codex project config file.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated files without writing them.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing target files even if they do not look generated.",
    )
    return parser.parse_args()


def default_config_path() -> Path:
    return Path(__file__).resolve().parent / "config.json"


def resolve_config_path(config_arg: str | None) -> Path:
    if config_arg:
        return Path(config_arg).expanduser().resolve()
    return default_config_path()


def resolve_repo_root(repo_root_arg: str) -> Path:
    repo_root = Path(repo_root_arg).expanduser().resolve()
    if not repo_root.exists():
        raise SystemExit(f"Repo root does not exist: {repo_root}")
    if not repo_root.is_dir():
        raise SystemExit(f"Repo root is not a directory: {repo_root}")
    return repo_root


def resolve_repo_path(repo_root: Path, path_arg: str) -> Path:
    path = Path(path_arg).expanduser()
    if path.is_absolute():
        return path.resolve()
    return (repo_root / path).resolve()


def load_optional_config(path: Path) -> dict:
    if not path.exists():
        return {}

    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON in {path}: {exc}") from exc

    if not isinstance(data, dict):
        raise SystemExit(f"Config file must contain a JSON object: {path}")

    return data


def load_source(path: Path) -> dict:
    try:
        data = json.loads(path.read_text())
    except FileNotFoundError as exc:
        raise SystemExit(f"Source MCP file not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON in {path}: {exc}") from exc

    mcp_servers = data.get("mcpServers")
    if not isinstance(mcp_servers, dict):
        raise SystemExit("Source config must contain an object field named 'mcpServers'")

    for name, config in mcp_servers.items():
        if not isinstance(name, str) or not name:
            raise SystemExit("Each MCP server name must be a non-empty string")
        if not isinstance(config, dict):
            raise SystemExit(f"MCP server '{name}' must map to an object")

    return data


def ensure_parent(path: Path, dry_run: bool) -> None:
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)


def format_toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def format_toml_key_segment(value: str) -> str:
    if not value:
        raise SystemExit("TOML key segments must be non-empty strings")
    if BARE_TOML_KEY_RE.fullmatch(value):
        return value
    return format_toml_string(value)


def format_toml_table_path(segments: list[str]) -> str:
    return ".".join(format_toml_key_segment(segment) for segment in segments)


def format_toml_scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if value != value or value in (float("inf"), float("-inf")):
            raise SystemExit("NaN and infinity are not supported in TOML output")
        return repr(value)
    if isinstance(value, str):
        return format_toml_string(value)
    raise SystemExit(f"Unsupported TOML scalar type: {type(value).__name__}")


def format_toml_array(values: list[object]) -> str:
    return "[" + ", ".join(format_toml_scalar(value) for value in values) + "]"


def add_toml_assignment(lines: list[str], key: str, value: object) -> None:
    key = format_toml_key_segment(key)
    if isinstance(value, list):
        lines.append(f"{key} = {format_toml_array(value)}")
        return
    lines.append(f"{key} = {format_toml_scalar(value)}")


def build_codex_config(source: dict) -> str:
    lines = [
        f"# {GENERATED_HEADER.splitlines()[0]}",
        f"# {GENERATED_HEADER.splitlines()[1]}",
        "",
    ]

    for server_name, server in source["mcpServers"].items():
        lines.append(f"[{format_toml_table_path(['mcp_servers', server_name])}]")

        mapped: list[tuple[str, object]] = []
        if "command" in server:
            mapped.append(("command", server["command"]))
        if "args" in server:
            mapped.append(("args", server["args"]))
        if "env" in server:
            mapped.append(("env", server["env"]))
        if "cwd" in server:
            mapped.append(("cwd", server["cwd"]))
        if "httpUrl" in server:
            mapped.append(("url", server["httpUrl"]))
        elif "url" in server:
            mapped.append(("url", server["url"]))
        if "headers" in server:
            mapped.append(("http_headers", server["headers"]))
        if "includeTools" in server:
            mapped.append(("enabled_tools", server["includeTools"]))
        if "excludeTools" in server:
            mapped.append(("disabled_tools", server["excludeTools"]))

        scalar_keys = {"command", "cwd", "url"}
        array_keys = {"args", "enabled_tools", "disabled_tools"}
        table_keys = {"env", "http_headers"}

        for key, value in mapped:
            if key in scalar_keys:
                if not isinstance(value, str):
                    raise SystemExit(
                        f"Codex field '{key}' for server '{server_name}' must be a string"
                    )
                add_toml_assignment(lines, key, value)
                continue

            if key in array_keys:
                if not isinstance(value, list):
                    raise SystemExit(
                        f"Codex field '{key}' for server '{server_name}' must be a list"
                    )
                add_toml_assignment(lines, key, value)
                continue

            if key in table_keys:
                if not isinstance(value, dict):
                    raise SystemExit(
                        f"Codex field '{key}' for server '{server_name}' must be an object"
                    )
                lines.append(
                    f"[{format_toml_table_path(['mcp_servers', server_name, key])}]"
                )
                for nested_key, nested_value in value.items():
                    if not isinstance(nested_key, str):
                        raise SystemExit(
                            f"Nested Codex key in '{key}' for server '{server_name}' must be a string"
                        )
                    add_toml_assignment(lines, nested_key, nested_value)
                continue

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def load_gemini_overrides(config: dict) -> dict:
    gemini = config.get("gemini", {})
    if not isinstance(gemini, dict):
        raise SystemExit("Config field 'gemini' must be an object")

    context_file_names = gemini.get("context_file_names", [])
    if not isinstance(context_file_names, list) or not all(
        isinstance(item, str) and item for item in context_file_names
    ):
        raise SystemExit(
            "Config field 'gemini.context_file_names' must be a list of non-empty strings"
        )

    return {"context": {"fileName": context_file_names}} if context_file_names else {}


def build_gemini_config(source: dict, overrides: dict) -> str:
    gemini_config = {
        "$schema": "https://raw.githubusercontent.com/google-gemini/gemini-cli/main/schemas/settings.schema.json",
        "_generatedComment": GENERATED_HEADER,
        "mcpServers": source["mcpServers"],
    }
    gemini_config.update(overrides)
    return json.dumps(gemini_config, indent=2, sort_keys=True) + "\n"


def is_generated_file(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        content = path.read_text()
        return any(marker in content for marker in GENERATED_MARKERS)
    except UnicodeDecodeError:
        return False


def write_output(path: Path, content: str, dry_run: bool, force: bool) -> None:
    if path.exists() and not force and not is_generated_file(path):
        message = (
            f"Refusing to overwrite existing non-generated file at {path}. "
            "Use --force to replace it."
        )
        if dry_run:
            print(f"DRY RUN: {message}")
            return
        raise SystemExit(message)

    if dry_run:
        print(f"=== {path} ===")
        print(content, end="")
        return

    ensure_parent(path, dry_run=False)
    path.write_text(content)
    print(f"WROTE: {path}")


def main() -> int:
    args = parse_args()
    repo_root = resolve_repo_root(args.repo_root)
    config_path = resolve_config_path(args.config)
    config = load_optional_config(config_path)
    source_path = resolve_repo_path(repo_root, args.source)
    source = load_source(source_path)
    gemini_overrides = load_gemini_overrides(config)

    gemini_target = resolve_repo_path(repo_root, args.gemini_target)
    codex_target = resolve_repo_path(repo_root, args.codex_target)

    write_output(
        gemini_target,
        build_gemini_config(source, gemini_overrides),
        args.dry_run,
        args.force,
    )
    write_output(codex_target, build_codex_config(source), args.dry_run, args.force)
    return 0


if __name__ == "__main__":
    sys.exit(main())
